# Generated by Django 4.0 on 2021-12-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productvariant_created_at_productvariant_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantprice',
            name='product_variant_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_one', to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='product_variant_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_three', to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='productvariantprice',
            name='product_variant_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_two', to='product.productvariant'),
        ),
    ]
